### ISSUE TITLE
compute_benchmark_age_prediction.py line 315 error

### ISSUE THREAD

**Issue by anthonyromyn** [meeg-ml-benchmarks/brain-age-benchmark-paper#52]
Hey brain-age benchmark team,

I've encountered an error that I'm having trouble solving. Running the shallow benchmark analysis on the chbp data, I'm getting the error in the picture below after cross-validation is done. 

![Screenshot (1332)](https://user-images.githubusercontent.com/37704753/163100870-f83df01f-71c6-4112-ba11-9a5024e0bc76.png)

line 315 `ys.loc[cv_splits[:, 1], 'cv_split'] = cv_splits[:, 0].astype(int)`

ys and cv_splits are different lengths, so cv_splits[:,0] has many more rows relative to ys, thus the code fails to find appropriate places for many of the cv_splits

`ys` length equals the number  of subjects
`cv_splits` length is ~3221 

Handcrafted, dummy, filterbank-riemann have all worked well. Haven't tried deep yet.
 
Thanks,
Anthony

**Comment by anthonyromyn** [comment]
Can now confirm the same happens with the deep model

**Comment by agramfort** [comment]
@robintibor @gemeinl @hubertjb would you have time to look? and see if you can replicate eg in the compute system in Freiburg?

**Comment by anthonyromyn** [comment]
Thanks @agramfort and all!

**Comment by hubertjb** [comment]
@anthonyromyn Thanks for reporting this issue! #53 should fix this.

**Comment by anthonyromyn** [comment]
Awesome thanks @hubertjb, juts ran a quick test and looks to have worked wonderfully, thanks!
