### ISSUE TITLE
compute_autoreject.py on TUAB erroring at epochs.pick_channels (line 62-68)

### ISSUE THREAD

**Issue by anthonyromyn** [meeg-ml-benchmarks/brain-age-benchmark-paper#54]
Hey all,

What is meant by the comment on line 62 in compute_autoreject.py? https://github.com/meeg-ml-benchmarks/brain-age-benchmark-paper/blob/09075642182f7d6448e110a8eb1764b9e5364b38/compute_autoreject.py#L62-L68

I'm getting an error while running the TUAB data at line 68 so I thought maybe line 62 is related/the answer?

Thanks
Anthony

**Comment by anthonyromyn** [comment]
Here it is @agramfort 

![Screenshot (1348)](https://user-images.githubusercontent.com/37704753/164265940-ad243bd4-e4e2-4628-8dd1-803d30f08769.png)

**Comment by agramfort** [comment]
can you try to debug? there must be a difference in data or mne/mne-bids
versions between our systems

**Comment by anthonyromyn** [comment]
Yeah for sure, will dig into it and report back in the next few days.

**Comment by anthonyromyn** [comment]
Okay awesome it's working well now. Long story short I just needed to remove some extra name mismatching to compute_autoreject.py and it works wonderfully! Thanks!

```
    if any(ch.startswith('EEG ') for ch in epochs.ch_names):
        epochs.rename_channels(
            {ch: ch.strip('EEG ') for ch in epochs.ch_names})
```
